---
title: "Assignment 1: Introduction"
author: "Yimei Du"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took biostatistics and GIS course in my undergrad and I use both R studio and ArcGIS for those two courses. For ArcGIS, we learned how to do basic map analysis and our final project is making a storymap showing the analysis we did for our own project. My project is assessing how the distance to subway station is going to affect the population density and house price in Brooklyn, NY. I did a 5-ring buffer analysis with different distance on both population density and house prices. For R, I mainly use that for statistical analysis. Basically we follow the tutorial generated by our professor and generate tables and graphs and do analysis. 

2. Are there any components of the course about which you feel confident?

> Answer: Maybe at the very beginning where we are learning how to use R studio. But I don't have too many experiences using that except copy and paste the script and make a few changes. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I have never used Github before so that is new to me. Also, I have only used R studio for statistical analysis so I am very new to any other functions that R has. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/yimeidu47/EDE_Fall2025.git

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
